#!/bin/bash
### BEGIN INIT INFO
# Provides:        archon
# Required-Start:  $network
# Required-Stop:   $network
# Default-Start:   2 3 4 5
# Default-Stop:    0 1 6
# Short-Description: Start/Stop Announce IP to Spark
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

start() {
	sh /bin/start_archon
}

stop() {
	sh /bin/stop_archon
}

case $1 in
  start|stop)
    $1
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Run as $0 "
    exit 1
    ;;
esac
